engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    checks:
      Similar code:
        enabled: true
      Identical code:
        enabled: true
ratings:
  paths:
  - lib/**
  - test/**
