sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4 
  - 2.5.1
before_install: gem install bundler

addons:
  code_climate:
    repo_token: c3ac3f05b0de80fccc9d3ab38c1589b21dd1c4036efc87338c2004aee132496c
